name: Build SDL Native

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - CMakeLists.txt
      - .github/workflows/build_sdl_native.yml      
  pull_request:
    paths:
      - CMakeLists.txt
      - .github/workflows/build_sdl_native.yml

jobs:
  windows:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get CMake
      uses: lukka/get-cmake@v3.29.4

    - name: Configure win-x64
      run: cmake -S "." -B build_win_64 -G "Visual Studio 17 2022" -A x64 -D CMAKE_SYSTEM_VERSION=10.0.26100.0
    - name: Build win-x64
      run: cmake --build build_win_64 --config Release

    - name: Configure win-arm64
      run: cmake -S "." -B build_win_arm64 -G "Visual Studio 17 2022" -A ARM64 -D CMAKE_SYSTEM_VERSION=10.0.26100.0
    - name: Build win-arm64
      run: cmake --build build_win_arm64 --config Release
    - name: Package Windows
      run: |
        mkdir bin/win-x64/native
        mkdir bin/win-arm64/native
        mv build_win_64\bin\Release\SDL3.dll bin/win-x64/native
        mv build_win_arm64\bin\Release\SDL3.dll bin/win-arm64/native
    - uses: actions/upload-artifact@v4
      with:
        name: libs_windows
        path: bin

  linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Get CMake
      uses: lukka/get-cmake@v3.29.4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install libsdl2-dev
    - name: Configure linux-x64
      run: cmake -S "." -B build_linux_64 -G Ninja -DCMAKE_BUILD_TYPE=Release
    - name: Build linux-x64
      run: cmake --build build_linux_64 --config Release --verbose --parallel

    # Linux artifact 
    - name: package_linux
      run: |
        mkdir -p bin/linux-x64/native
        mv build_linux_64/lib/libSDL3.so.0.2.10 bin/linux-x64/native/libSDL3.so
    - uses: actions/upload-artifact@v4
      with:
        name: libs_linux
        path: bin

  macos:
    runs-on: macos-14
    steps:
    - uses: actions/checkout@v4

    - name: Get CMake
      uses: lukka/get-cmake@v3.29.4

    - name: Configure osx-universal
      run: cmake -S "." -B build_osx -G Ninja -DCMAKE_BUILD_TYPE=Release -D"CMAKE_OSX_ARCHITECTURES=x86_64;arm64"
    - name: Build osx-universal
      run: cmake --build build_osx --config Release --verbose --parallel

    # macOS artifacts
    - name: package_osx
      run: |
        mkdir -p bin/osx/native
        mv build_osx/lib/libSDL3.0.dylib bin/osx/native/libSDL3.dylib
    - uses: actions/upload-artifact@v4
      with:
        name: libs_osx
        path: bin

  update_native_libs:
    name: Update native libs
    runs-on: ubuntu-latest
    needs: [windows, linux, macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Download windows lib
        uses: actions/download-artifact@v4
        with:
          name: libs_windows
          path: src/Alimer.Bindings.SDL/runtimes
      - name: Download ubuntu lib
        uses: actions/download-artifact@v4
        with:
          name: libs_linux
          path: src/Alimer.Bindings.SDL/runtimes
      - name: Download macos lib
        uses: actions/download-artifact@v4
        with:
          name: libs_osx
          path: src/Alimer.Bindings.SDL/runtimes
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: src/Alimer.Bindings.SDL/runtimes
      - name: Commit changes
        uses: EndBug/add-and-commit@v9.1.4
        with:
          message: Updated native libs
          committer_name: GitHub Actions
          committer_email: actions@github.com